// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class Active_Contract
    {

        /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.ScriptManager _ToolkitScriptManager1;

        protected global::System.Web.UI.ScriptManager ToolkitScriptManager1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ToolkitScriptManager1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ToolkitScriptManager1 != null)
                {
                }

                _ToolkitScriptManager1 = value;
                if (_ToolkitScriptManager1 != null)
                {
                }
            }
        }

        /// <summary>
    /// up1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.UpdatePanel _up1;

        protected global::System.Web.UI.UpdatePanel up1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _up1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_up1 != null)
                {
                }

                _up1 = value;
                if (_up1 != null)
                {
                }
            }
        }

        /// <summary>
    /// gd1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd1;

        protected global::System.Web.UI.WebControls.GridView gd1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd1 != null)
                {
                }

                _gd1 = value;
                if (_gd1 != null)
                {
                }
            }
        }

        /// <summary>
    /// visible1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _visible1;

        protected global::System.Web.UI.WebControls.Label visible1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _visible1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_visible1 != null)
                {
                }

                _visible1 = value;
                if (_visible1 != null)
                {
                }
            }
        }

        /// <summary>
    /// gd2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd2;

        protected global::System.Web.UI.WebControls.GridView gd2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd2 != null)
                {
                }

                _gd2 = value;
                if (_gd2 != null)
                {
                }
            }
        }

        /// <summary>
    /// visible2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _visible2;

        protected global::System.Web.UI.WebControls.Label visible2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _visible2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_visible2 != null)
                {
                }

                _visible2 = value;
                if (_visible2 != null)
                {
                }
            }
        }

        /// <summary>
    /// Button3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Button3;

        protected global::System.Web.UI.WebControls.Button Button3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Button3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Button3 != null)
                {
                }

                _Button3 = value;
                if (_Button3 != null)
                {
                }
            }
        }

        /// <summary>
    /// Button1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Button1;

        protected global::System.Web.UI.WebControls.Button Button1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Button1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Button1 != null)
                {
                }

                _Button1 = value;
                if (_Button1 != null)
                {
                }
            }
        }
    }
}
