// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class WebForm2
    {

        /// <summary>
    /// lblMsg control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblMsg;

        protected global::System.Web.UI.WebControls.Label lblMsg
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblMsg;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblMsg != null)
                {
                }

                _lblMsg = value;
                if (_lblMsg != null)
                {
                }
            }
        }

        /// <summary>
    /// Label1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Label1;

        protected global::System.Web.UI.WebControls.Label Label1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Label1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Label1 != null)
                {
                }

                _Label1 = value;
                if (_Label1 != null)
                {
                }
            }
        }

        /// <summary>
    /// txtUNM control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txtUNM;

        protected global::System.Web.UI.WebControls.TextBox txtUNM
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtUNM;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtUNM != null)
                {
                }

                _txtUNM = value;
                if (_txtUNM != null)
                {
                }
            }
        }

        /// <summary>
    /// Label2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Label2;

        protected global::System.Web.UI.WebControls.Label Label2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Label2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Label2 != null)
                {
                }

                _Label2 = value;
                if (_Label2 != null)
                {
                }
            }
        }

        /// <summary>
    /// txtPWD control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txtPWD;

        protected global::System.Web.UI.WebControls.TextBox txtPWD
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txtPWD;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txtPWD != null)
                {
                }

                _txtPWD = value;
                if (_txtPWD != null)
                {
                }
            }
        }

        /// <summary>
    /// imgLogIn control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Image _imgLogIn;

        protected global::System.Web.UI.WebControls.Image imgLogIn
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _imgLogIn;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_imgLogIn != null)
                {
                }

                _imgLogIn = value;
                if (_imgLogIn != null)
                {
                }
            }
        }

        /// <summary>
    /// btnLogIn control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _btnLogIn;

        protected global::System.Web.UI.WebControls.Button btnLogIn
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnLogIn;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnLogIn != null)
                {
                }

                _btnLogIn = value;
                if (_btnLogIn != null)
                {
                }
            }
        }
    }
}
