// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class Master_Data
    {

        /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.ScriptManager _ToolkitScriptManager1;

        protected global::System.Web.UI.ScriptManager ToolkitScriptManager1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ToolkitScriptManager1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ToolkitScriptManager1 != null)
                {
                }

                _ToolkitScriptManager1 = value;
                if (_ToolkitScriptManager1 != null)
                {
                }
            }
        }

        /// <summary>
    /// up1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.UpdatePanel _up1;

        protected global::System.Web.UI.UpdatePanel up1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _up1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_up1 != null)
                {
                }

                _up1 = value;
                if (_up1 != null)
                {
                }
            }
        }

        /// <summary>
    /// drop_ter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.DropDownList _drop_ter;

        protected global::System.Web.UI.WebControls.DropDownList drop_ter
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _drop_ter;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_drop_ter != null)
                {
                }

                _drop_ter = value;
                if (_drop_ter != null)
                {
                }
            }
        }

        /// <summary>
    /// drp_Filter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.DropDownList _drp_Filter;

        protected global::System.Web.UI.WebControls.DropDownList drp_Filter
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _drp_Filter;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_drp_Filter != null)
                {
                }

                _drp_Filter = value;
                if (_drp_Filter != null)
                {
                }
            }
        }

        /// <summary>
    /// btn_drop control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _btn_drop;

        protected global::System.Web.UI.WebControls.Button btn_drop
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btn_drop;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btn_drop != null)
                {
                }

                _btn_drop = value;
                if (_btn_drop != null)
                {
                }
            }
        }

        /// <summary>
    /// Lbl_Error control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Lbl_Error;

        protected global::System.Web.UI.WebControls.Label Lbl_Error
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Lbl_Error;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Lbl_Error != null)
                {
                }

                _Lbl_Error = value;
                if (_Lbl_Error != null)
                {
                }
            }
        }

        /// <summary>
    /// gd1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd1;

        protected global::System.Web.UI.WebControls.GridView gd1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd1 != null)
                {
                }

                _gd1 = value;
                if (_gd1 != null)
                {
                }
            }
        }

        /// <summary>
    /// Btn_Gd1_Save control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Btn_Gd1_Save;

        protected global::System.Web.UI.WebControls.Button Btn_Gd1_Save
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Btn_Gd1_Save;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Btn_Gd1_Save != null)
                {
                }

                _Btn_Gd1_Save = value;
                if (_Btn_Gd1_Save != null)
                {
                }
            }
        }
    }
}
