// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class MDM_Search1
    {

        /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.ScriptManager _ToolkitScriptManager1;

        protected global::System.Web.UI.ScriptManager ToolkitScriptManager1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ToolkitScriptManager1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ToolkitScriptManager1 != null)
                {
                }

                _ToolkitScriptManager1 = value;
                if (_ToolkitScriptManager1 != null)
                {
                }
            }
        }

        /// <summary>
    /// up1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.UpdatePanel _up1;

        protected global::System.Web.UI.UpdatePanel up1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _up1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_up1 != null)
                {
                }

                _up1 = value;
                if (_up1 != null)
                {
                }
            }
        }

        /// <summary>
    /// Un_label control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.HtmlControls.HtmlGenericControl _Un_label;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Un_label
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Un_label;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Un_label != null)
                {
                }

                _Un_label = value;
                if (_Un_label != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_un control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_un;

        protected global::System.Web.UI.WebControls.GridView gd_un
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_un;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_un != null)
                {
                }

                _gd_un = value;
                if (_gd_un != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_name;

        protected global::System.Web.UI.WebControls.TextBox txt_name
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_name;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_name != null)
                {
                }

                _txt_name = value;
                if (_txt_name != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender1;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender1 != null)
                {
                }

                _AutoCompleteExtender1 = value;
                if (_AutoCompleteExtender1 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_add control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_add;

        protected global::System.Web.UI.WebControls.TextBox txt_add
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_add;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_add != null)
                {
                }

                _txt_add = value;
                if (_txt_add != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender3;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender3 != null)
                {
                }

                _AutoCompleteExtender3 = value;
                if (_AutoCompleteExtender3 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_city control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_city;

        protected global::System.Web.UI.WebControls.TextBox txt_city
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_city;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_city != null)
                {
                }

                _txt_city = value;
                if (_txt_city != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender4;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender4
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender4;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender4 != null)
                {
                }

                _AutoCompleteExtender4 = value;
                if (_AutoCompleteExtender4 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_st control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_st;

        protected global::System.Web.UI.WebControls.TextBox txt_st
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_st;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_st != null)
                {
                }

                _txt_st = value;
                if (_txt_st != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender5;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender5
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender5;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender5 != null)
                {
                }

                _AutoCompleteExtender5 = value;
                if (_AutoCompleteExtender5 != null)
                {
                }
            }
        }

        /// <summary>
    /// Zip_txt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _Zip_txt;

        protected global::System.Web.UI.WebControls.TextBox Zip_txt
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Zip_txt;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Zip_txt != null)
                {
                }

                _Zip_txt = value;
                if (_Zip_txt != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender2;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender2 != null)
                {
                }

                _AutoCompleteExtender2 = value;
                if (_AutoCompleteExtender2 != null)
                {
                }
            }
        }

        /// <summary>
    /// Button1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Button1;

        protected global::System.Web.UI.WebControls.Button Button1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Button1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Button1 != null)
                {
                }

                _Button1 = value;
                if (_Button1 != null)
                {
                }
            }
        }

        /// <summary>
    /// ERR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _ERR;

        protected global::System.Web.UI.WebControls.Label ERR
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ERR;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ERR != null)
                {
                }

                _ERR = value;
                if (_ERR != null)
                {
                }
            }
        }

        /// <summary>
    /// gd1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd1;

        protected global::System.Web.UI.WebControls.GridView gd1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd1 != null)
                {
                }

                _gd1 = value;
                if (_gd1 != null)
                {
                }
            }
        }

        /// <summary>
    /// gd2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd2;

        protected global::System.Web.UI.WebControls.GridView gd2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd2 != null)
                {
                }

                _gd2 = value;
                if (_gd2 != null)
                {
                }
            }
        }

        /// <summary>
    /// err3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _err3;

        protected global::System.Web.UI.WebControls.Label err3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _err3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_err3 != null)
                {
                }

                _err3 = value;
                if (_err3 != null)
                {
                }
            }
        }

        /// <summary>
    /// Button2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Button2;

        protected global::System.Web.UI.WebControls.Button Button2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Button2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Button2 != null)
                {
                }

                _Button2 = value;
                if (_Button2 != null)
                {
                }
            }
        }

        /// <summary>
    /// manual_label control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.HtmlControls.HtmlGenericControl _manual_label;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl manual_label
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _manual_label;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_manual_label != null)
                {
                }

                _manual_label = value;
                if (_manual_label != null)
                {
                }
            }
        }

        /// <summary>
    /// manual_tabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.HtmlControls.HtmlTable _manual_tabel;

        protected global::System.Web.UI.HtmlControls.HtmlTable manual_tabel
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _manual_tabel;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_manual_tabel != null)
                {
                }

                _manual_tabel = value;
                if (_manual_tabel != null)
                {
                }
            }
        }

        /// <summary>
    /// TextBox1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _TextBox1;

        protected global::System.Web.UI.WebControls.TextBox TextBox1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _TextBox1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_TextBox1 != null)
                {
                }

                _TextBox1 = value;
                if (_TextBox1 != null)
                {
                }
            }
        }

        /// <summary>
    /// TextBox2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _TextBox2;

        protected global::System.Web.UI.WebControls.TextBox TextBox2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _TextBox2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_TextBox2 != null)
                {
                }

                _TextBox2 = value;
                if (_TextBox2 != null)
                {
                }
            }
        }

        /// <summary>
    /// TextBox3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _TextBox3;

        protected global::System.Web.UI.WebControls.TextBox TextBox3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _TextBox3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_TextBox3 != null)
                {
                }

                _TextBox3 = value;
                if (_TextBox3 != null)
                {
                }
            }
        }

        /// <summary>
    /// TextBox4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _TextBox4;

        protected global::System.Web.UI.WebControls.TextBox TextBox4
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _TextBox4;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_TextBox4 != null)
                {
                }

                _TextBox4 = value;
                if (_TextBox4 != null)
                {
                }
            }
        }

        /// <summary>
    /// TextBox5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _TextBox5;

        protected global::System.Web.UI.WebControls.TextBox TextBox5
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _TextBox5;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_TextBox5 != null)
                {
                }

                _TextBox5 = value;
                if (_TextBox5 != null)
                {
                }
            }
        }

        /// <summary>
    /// Man_match control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Man_match;

        protected global::System.Web.UI.WebControls.Button Man_match
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Man_match;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Man_match != null)
                {
                }

                _Man_match = value;
                if (_Man_match != null)
                {
                }
            }
        }

        /// <summary>
    /// err2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _err2;

        protected global::System.Web.UI.WebControls.Label err2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _err2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_err2 != null)
                {
                }

                _err2 = value;
                if (_err2 != null)
                {
                }
            }
        }
    }
}
