// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class MDM_Search
    {

        /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.ScriptManager _ToolkitScriptManager1;

        protected global::System.Web.UI.ScriptManager ToolkitScriptManager1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ToolkitScriptManager1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ToolkitScriptManager1 != null)
                {
                }

                _ToolkitScriptManager1 = value;
                if (_ToolkitScriptManager1 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_name;

        protected global::System.Web.UI.WebControls.TextBox txt_name
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_name;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_name != null)
                {
                }

                _txt_name = value;
                if (_txt_name != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender1;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender1 != null)
                {
                }

                _AutoCompleteExtender1 = value;
                if (_AutoCompleteExtender1 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_add control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_add;

        protected global::System.Web.UI.WebControls.TextBox txt_add
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_add;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_add != null)
                {
                }

                _txt_add = value;
                if (_txt_add != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender3;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender3
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender3;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender3 != null)
                {
                }

                _AutoCompleteExtender3 = value;
                if (_AutoCompleteExtender3 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_city control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_city;

        protected global::System.Web.UI.WebControls.TextBox txt_city
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_city;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_city != null)
                {
                }

                _txt_city = value;
                if (_txt_city != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender4;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender4
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender4;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender4 != null)
                {
                }

                _AutoCompleteExtender4 = value;
                if (_AutoCompleteExtender4 != null)
                {
                }
            }
        }

        /// <summary>
    /// txt_st control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _txt_st;

        protected global::System.Web.UI.WebControls.TextBox txt_st
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _txt_st;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_txt_st != null)
                {
                }

                _txt_st = value;
                if (_txt_st != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender5;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender5
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender5;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender5 != null)
                {
                }

                _AutoCompleteExtender5 = value;
                if (_AutoCompleteExtender5 != null)
                {
                }
            }
        }

        /// <summary>
    /// Zip_txt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.TextBox _Zip_txt;

        protected global::System.Web.UI.WebControls.TextBox Zip_txt
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Zip_txt;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Zip_txt != null)
                {
                }

                _Zip_txt = value;
                if (_Zip_txt != null)
                {
                }
            }
        }

        /// <summary>
    /// AutoCompleteExtender2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::AjaxControlToolkit.AutoCompleteExtender _AutoCompleteExtender2;

        protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _AutoCompleteExtender2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_AutoCompleteExtender2 != null)
                {
                }

                _AutoCompleteExtender2 = value;
                if (_AutoCompleteExtender2 != null)
                {
                }
            }
        }

        /// <summary>
    /// Button1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Button _Button1;

        protected global::System.Web.UI.WebControls.Button Button1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Button1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Button1 != null)
                {
                }

                _Button1 = value;
                if (_Button1 != null)
                {
                }
            }
        }

        /// <summary>
    /// ERR control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _ERR;

        protected global::System.Web.UI.WebControls.Label ERR
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ERR;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ERR != null)
                {
                }

                _ERR = value;
                if (_ERR != null)
                {
                }
            }
        }

        /// <summary>
    /// gd1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd1;

        protected global::System.Web.UI.WebControls.GridView gd1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd1 != null)
                {
                }

                _gd1 = value;
                if (_gd1 != null)
                {
                }
            }
        }

        /// <summary>
    /// sales_details control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _sales_details;

        protected global::System.Web.UI.WebControls.Label sales_details
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _sales_details;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_sales_details != null)
                {
                }

                _sales_details = value;
                if (_sales_details != null)
                {
                }
            }
        }

        /// <summary>
    /// comapany_name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _comapany_name;

        protected global::System.Web.UI.WebControls.Label comapany_name
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _comapany_name;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_comapany_name != null)
                {
                }

                _comapany_name = value;
                if (_comapany_name != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSani control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSani;

        protected global::System.Web.UI.WebControls.Label lblSani
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSani;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSani != null)
                {
                }

                _lblSani = value;
                if (_lblSani != null)
                {
                }
            }
        }

        /// <summary>
    /// lblPrevantics control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblPrevantics;

        protected global::System.Web.UI.WebControls.Label lblPrevantics
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblPrevantics;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblPrevantics != null)
                {
                }

                _lblPrevantics = value;
                if (_lblPrevantics != null)
                {
                }
            }
        }

        /// <summary>
    /// lblBabyWipes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblBabyWipes;

        protected global::System.Web.UI.WebControls.Label lblBabyWipes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblBabyWipes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblBabyWipes != null)
                {
                }

                _lblBabyWipes = value;
                if (_lblBabyWipes != null)
                {
                }
            }
        }

        /// <summary>
    /// lblOthers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblOthers;

        protected global::System.Web.UI.WebControls.Label lblOthers
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblOthers;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblOthers != null)
                {
                }

                _lblOthers = value;
                if (_lblOthers != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSpecial control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSpecial;

        protected global::System.Web.UI.WebControls.Label lblSpecial
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSpecial;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSpecial != null)
                {
                }

                _lblSpecial = value;
                if (_lblSpecial != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSaniHands control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSaniHands;

        protected global::System.Web.UI.WebControls.Label lblSaniHands
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSaniHands;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSaniHands != null)
                {
                }

                _lblSaniHands = value;
                if (_lblSaniHands != null)
                {
                }
            }
        }

        /// <summary>
    /// lblIodine control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblIodine;

        protected global::System.Web.UI.WebControls.Label lblIodine
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblIodine;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblIodine != null)
                {
                }

                _lblIodine = value;
                if (_lblIodine != null)
                {
                }
            }
        }

        /// <summary>
    /// lblHygea control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblHygea;

        protected global::System.Web.UI.WebControls.Label lblHygea
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblHygea;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblHygea != null)
                {
                }

                _lblHygea = value;
                if (_lblHygea != null)
                {
                }
            }
        }

        /// <summary>
    /// lblAdultWipes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblAdultWipes;

        protected global::System.Web.UI.WebControls.Label lblAdultWipes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblAdultWipes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblAdultWipes != null)
                {
                }

                _lblAdultWipes = value;
                if (_lblAdultWipes != null)
                {
                }
            }
        }

        /// <summary>
    /// lblCompAcc control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblCompAcc;

        protected global::System.Web.UI.WebControls.Label lblCompAcc
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblCompAcc;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblCompAcc != null)
                {
                }

                _lblCompAcc = value;
                if (_lblCompAcc != null)
                {
                }
            }
        }

        /// <summary>
    /// lblTotal control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblTotal;

        protected global::System.Web.UI.WebControls.Label lblTotal
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblTotal;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblTotal != null)
                {
                }

                _lblTotal = value;
                if (_lblTotal != null)
                {
                }
            }
        }
    }
}
