// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class MDM_Network
    {

        /// <summary>
    /// ToolkitScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.ScriptManager _ToolkitScriptManager1;

        protected global::System.Web.UI.ScriptManager ToolkitScriptManager1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ToolkitScriptManager1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ToolkitScriptManager1 != null)
                {
                }

                _ToolkitScriptManager1 = value;
                if (_ToolkitScriptManager1 != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_company control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_company;

        protected global::System.Web.UI.WebControls.GridView gd_company
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_company;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_company != null)
                {
                }

                _gd_company = value;
                if (_gd_company != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_IDN control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_IDN;

        protected global::System.Web.UI.WebControls.GridView gd_IDN
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_IDN;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_IDN != null)
                {
                }

                _gd_IDN = value;
                if (_gd_IDN != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_parent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_parent;

        protected global::System.Web.UI.WebControls.GridView gd_parent
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_parent;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_parent != null)
                {
                }

                _gd_parent = value;
                if (_gd_parent != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_child control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_child;

        protected global::System.Web.UI.WebControls.GridView gd_child
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_child;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_child != null)
                {
                }

                _gd_child = value;
                if (_gd_child != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_network control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_network;

        protected global::System.Web.UI.WebControls.GridView gd_network
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_network;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_network != null)
                {
                }

                _gd_network = value;
                if (_gd_network != null)
                {
                }
            }
        }

        /// <summary>
    /// gd_aff control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.GridView _gd_aff;

        protected global::System.Web.UI.WebControls.GridView gd_aff
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _gd_aff;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_gd_aff != null)
                {
                }

                _gd_aff = value;
                if (_gd_aff != null)
                {
                }
            }
        }

        /// <summary>
    /// sales_details control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _sales_details;

        protected global::System.Web.UI.WebControls.Label sales_details
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _sales_details;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_sales_details != null)
                {
                }

                _sales_details = value;
                if (_sales_details != null)
                {
                }
            }
        }

        /// <summary>
    /// comapany_name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _comapany_name;

        protected global::System.Web.UI.WebControls.Label comapany_name
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _comapany_name;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_comapany_name != null)
                {
                }

                _comapany_name = value;
                if (_comapany_name != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSani control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSani;

        protected global::System.Web.UI.WebControls.Label lblSani
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSani;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSani != null)
                {
                }

                _lblSani = value;
                if (_lblSani != null)
                {
                }
            }
        }

        /// <summary>
    /// lblPrevantics control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblPrevantics;

        protected global::System.Web.UI.WebControls.Label lblPrevantics
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblPrevantics;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblPrevantics != null)
                {
                }

                _lblPrevantics = value;
                if (_lblPrevantics != null)
                {
                }
            }
        }

        /// <summary>
    /// lblBabyWipes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblBabyWipes;

        protected global::System.Web.UI.WebControls.Label lblBabyWipes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblBabyWipes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblBabyWipes != null)
                {
                }

                _lblBabyWipes = value;
                if (_lblBabyWipes != null)
                {
                }
            }
        }

        /// <summary>
    /// lblOthers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblOthers;

        protected global::System.Web.UI.WebControls.Label lblOthers
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblOthers;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblOthers != null)
                {
                }

                _lblOthers = value;
                if (_lblOthers != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSpecial control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSpecial;

        protected global::System.Web.UI.WebControls.Label lblSpecial
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSpecial;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSpecial != null)
                {
                }

                _lblSpecial = value;
                if (_lblSpecial != null)
                {
                }
            }
        }

        /// <summary>
    /// lblSaniHands control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblSaniHands;

        protected global::System.Web.UI.WebControls.Label lblSaniHands
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblSaniHands;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblSaniHands != null)
                {
                }

                _lblSaniHands = value;
                if (_lblSaniHands != null)
                {
                }
            }
        }

        /// <summary>
    /// lblIodine control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblIodine;

        protected global::System.Web.UI.WebControls.Label lblIodine
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblIodine;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblIodine != null)
                {
                }

                _lblIodine = value;
                if (_lblIodine != null)
                {
                }
            }
        }

        /// <summary>
    /// lblHygea control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblHygea;

        protected global::System.Web.UI.WebControls.Label lblHygea
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblHygea;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblHygea != null)
                {
                }

                _lblHygea = value;
                if (_lblHygea != null)
                {
                }
            }
        }

        /// <summary>
    /// lblAdultWipes control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblAdultWipes;

        protected global::System.Web.UI.WebControls.Label lblAdultWipes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblAdultWipes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblAdultWipes != null)
                {
                }

                _lblAdultWipes = value;
                if (_lblAdultWipes != null)
                {
                }
            }
        }

        /// <summary>
    /// lblCompAcc control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblCompAcc;

        protected global::System.Web.UI.WebControls.Label lblCompAcc
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblCompAcc;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblCompAcc != null)
                {
                }

                _lblCompAcc = value;
                if (_lblCompAcc != null)
                {
                }
            }
        }

        /// <summary>
    /// lblTotal control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _lblTotal;

        protected global::System.Web.UI.WebControls.Label lblTotal
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _lblTotal;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_lblTotal != null)
                {
                }

                _lblTotal = value;
                if (_lblTotal != null)
                {
                }
            }
        }
    }
}
