// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Web.SessionState;
using System.Configuration;
using System.Web.Caching;
using System.Collections.Specialized;
using System.Web.UI.WebControls.WebParts;
using System.Data;
using System.Diagnostics;
using Microsoft.VisualBasic;
using System.Web.UI.WebControls;
using System.Text;
using System.Web.Profile;
using System.Web;
using System.Linq;
using System.Web.Security;
using System.Collections.Generic;
using System.Collections;
using System.Web.UI.HtmlControls;
using System.Web.UI;
using System.Text.RegularExpressions;
using System;
using System.Xml.Linq;

namespace Database_1
{
    public partial class Site1
    {

        /// <summary>
    /// head control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.ContentPlaceHolder _head;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder head
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _head;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_head != null)
                {
                }

                _head = value;
                if (_head != null)
                {
                }
            }
        }

        /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.HtmlControls.HtmlForm _form1;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _form1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_form1 != null)
                {
                }

                _form1 = value;
                if (_form1 != null)
                {
                }
            }
        }

        /// <summary>
    /// Main_Menu control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Main_Menu;

        protected global::System.Web.UI.WebControls.Label Main_Menu
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Main_Menu;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Main_Menu != null)
                {
                }

                _Main_Menu = value;
                if (_Main_Menu != null)
                {
                }
            }
        }

        /// <summary>
    /// Page_name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Page_name;

        protected global::System.Web.UI.WebControls.Label Page_name
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Page_name;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Page_name != null)
                {
                }

                _Page_name = value;
                if (_Page_name != null)
                {
                }
            }
        }

        /// <summary>
    /// Label1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.Label _Label1;

        protected global::System.Web.UI.WebControls.Label Label1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Label1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_Label1 != null)
                {
                }

                _Label1 = value;
                if (_Label1 != null)
                {
                }
            }
        }

        /// <summary>
    /// ContentPlaceHolder1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private global::System.Web.UI.WebControls.ContentPlaceHolder _ContentPlaceHolder1;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _ContentPlaceHolder1;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_ContentPlaceHolder1 != null)
                {
                }

                _ContentPlaceHolder1 = value;
                if (_ContentPlaceHolder1 != null)
                {
                }
            }
        }
    }
}
